# Generated by Django 4.2.7 on 2023-11-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0002_comment_views_topic_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
