# Generated by Django 4.2.7 on 2023-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
