# Generated by Django 4.2.7 on 2023-11-10 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_alter_topic_slug_alter_topic_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
    ]
