# Generated by Django 4.2.7 on 2023-11-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0006_alter_topic_options_alter_topic_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topics.category"
            ),
        ),
    ]
