# Generated by Django 4.2.7 on 2023-11-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0007_alter_topic_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="content",
            field=models.TextField(max_length=20000),
        ),
    ]
