# Generated by Django 4.2.7 on 2023-11-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0009_remove_topic_category_topic_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="content",
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="views",
            name="view_counts",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
