# Generated by Django 4.2.7 on 2023-11-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0011_alter_topic_views_alter_topic_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="category",
        ),
        migrations.AddField(
            model_name="topic",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="topics.category",
            ),
        ),
    ]
